on:
  push:
    tags:
      - v[0-9]+.*

name: Publish

permissions:
  id-token: write

jobs:
  crates_publish:
    name: Publish (crates.io)

    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4

      - name: Update version
        shell: bash
        run: |
          VERSION=$(git describe --tags | grep -o '^v\?[0-9]\+\.[0-9]\+\.[0-9]\+' | sed 's/^v//')
          sed "s/^version = \".*\"$/version = \"$VERSION\"/" Cargo.toml > Cargo.toml.temp
          mv -f Cargo.toml.temp Cargo.toml

      - run: rustup toolchain install nightly --profile minimal --no-self-update

      - uses: Swatinem/rust-cache@v2

      - name: cargo login
        run: cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: "cargo release publish"
        run: |-
          cargo publish \
            --allow-dirty \
            --no-verify \
